server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/approval
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082/realms/reeste