reeste:
  services:
    budget:
      uri: http://127.0.0.1:8081
      registration-id: keycloak
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8082/realms/reeste
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: W2YzURkyR9d8KbpYCsSdarIvtoly9Riy
            scope:
              - openid
              - edit_budgets
              - view_budgets
              - microprofile-jwt