server:
  port: 8081
logging:
  level:
    sql: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reeste
    username: reeste
    password: oY0uZGukMr
  flyway:
    schemas:
      - public
      - reeste
    baselineOnMigrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082/realms/reeste